### ISSUE TITLE
forcedroid fails to create new Android project

### ISSUE THREAD

**Issue by davidfekke** [forcedotcom/SalesforceMobileSDK-Package#52]
I have Node.js 6.11.3 installed with macOS 10.12.6. I am getting the following error when I try to create a new Android app or add a plugin to an existing app;

```
forcedroid create --apptype=hybrid_remote --appname="SFTest" --packagename=com.swyftmobile.sftest --organization="Swyft Technology" --startpage="/one/one.app"
Enter output directory for your app (leave empty for the current directory):

********************************************************************************
*
*   Creating android hybrid_remote application using Salesforce Mobile SDK
*     with app name:        SFTest
*          package name:    com.swyftmobile.sftest
*          organization:    Swyft Technology
*
*     in:                   SFTest
*
*     from template repo:   https://github.com/forcedotcom/SalesforceMobileSDK-Templates#v5.0.0
*          template path:   HybridRemoteTemplate
*          start page:      /one/one.app
*          plugin repo:     https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v5.0.0
*
********************************************************************************

Creating a new cordova project.
/Users/davidfekke/Documents/android/projects/SFTest /Users/davidfekke/Documents/android/projects
com.swyftmobile.sftest@1.0.0 /Users/davidfekke/Documents/android/projects/SFTest
└─┬ shelljs@0.7.0
  ├─┬ glob@7.1.2
  │ ├── fs.realpath@1.0.0
  │ ├─┬ inflight@1.0.6
  │ │ └── wrappy@1.0.2
  │ ├── inherits@2.0.3
  │ ├─┬ minimatch@3.0.4
  │ │ └─┬ brace-expansion@1.1.8
  │ │   ├── balanced-match@1.0.0
  │ │   └── concat-map@0.0.1
  │ ├── once@1.4.0
  │ └── path-is-absolute@1.0.1
  ├── interpret@1.0.3
  └─┬ rechoir@0.6.2
    └─┬ resolve@1.4.0
      └── path-parse@1.0.5

/Users/davidfekke/Documents/android/projects
/Users/davidfekke/Documents/android/projects/SFTest /Users/davidfekke/Documents/android/projects
Using cordova-fetch for cordova-android@6.1.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.swyftmobile.sftest
	Name: SFTest
	Activity: MainActivity
	Android target: android-25
Subproject Path: CordovaLib
Android project created with cordova-android@6.1.0
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android
ANDROID_HOME=/Users/davidfekke/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
Failed to install 'cordova-plugin-whitelist': CordovaError: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: /Users/davidfekke/Library/Android/sdk/tools/templates/gradle/wrapper
    at Object.module.exports.check_gradle (/Users/davidfekke/Documents/android/projects/SFTest/platforms/android/cordova/lib/check_reqs.js:90:25)
    at GradleBuilder.prepEnv (/Users/davidfekke/Documents/android/projects/SFTest/platforms/android/cordova/lib/builders/GradleBuilder.js:161:23)
    at Api.module.exports.runClean (/Users/davidfekke/Documents/android/projects/SFTest/platforms/android/cordova/lib/build.js:131:20)
    at /Users/davidfekke/Documents/android/projects/SFTest/platforms/android/cordova/Api.js:392:50
    at _fulfilled (/Users/davidfekke/Documents/android/projects/SFTest/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/davidfekke/Documents/android/projects/SFTest/platforms/android/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/davidfekke/Documents/android/projects/SFTest/platforms/android/cordova/node_modules/q/q.js:796:13)
    at /Users/davidfekke/Documents/android/projects/SFTest/platforms/android/cordova/node_modules/q/q.js:604:44
    at runSingle (/Users/davidfekke/Documents/android/projects/SFTest/platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/davidfekke/Documents/android/projects/SFTest/platforms/android/cordova/node_modules/q/q.js:125:13)
Failed to restore plugin "cordova-plugin-whitelist" from config.xml. You might need to try adding it again. Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: /Users/davidfekke/Library/Android/sdk/tools/templates/gradle/wrapper
--save flag or autosave detected
Saving android@~6.1.0 into config.xml file ...
/Users/davidfekke/Documents/android/projects
forcedroid create failed

Command failed: cordova platform add android@6.1.0
```

**Comment by wmathurin** [comment]
Please try again with the latest version of forcedroid (5.2).

**Comment by davidfekke** [comment]
I upgraded to forcedroid 5.3, and I was able to get it working.
