### ISSUE TITLE
forcehybrid: CordovaError: Failed to fetch plugin cordova-plugin-device@1.0.1 via registry.

### ISSUE THREAD

**Issue by davidfekke** [forcedotcom/SalesforceMobileSDK-Package#96]
I am getting the an error when I try to use the forcehybrid tool to create a new app. Here is the command I am using to create the app;

```
forcehybrid create --platform=android --apptype=hybrid_remote --appname=SFHybridTest --packagename=com.swyftmobile.sfhybridtest --organization="Swyft Technology L.L.C." --startpage=one/one.app
```

I am using forcehybrid version 6.0. I am also using Node.js version 8.9.5. 

Here is the full text from the console when I try to create a new app;

```

********************************************************************************
*
*   Creating android hybrid_remote application using Salesforce Mobile SDK
*     with app name:        SFHybridTest
*          package name:    com.swyftmobile.sfhybridtest
*          organization:    Swyft Technology L.L.C.
*
*     in:                   SFHybridTest
*
*     from template repo:   https://github.com/forcedotcom/SalesforceMobileSDK-Templates#v6.0.0
*          template path:   HybridRemoteTemplate
*          start page:      one/one.app
*          plugin repo:     https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v6.0.0
*
********************************************************************************

Creating a new cordova project.
/Users/davidfekke/Documents/android/projects/SFHybridTest /Users/davidfekke/Documents/android/projects
+ shelljs@0.7.0
added 16 packages in 1.473s
/Users/davidfekke/Documents/android/projects
/Users/davidfekke/Documents/android/projects/SFHybridTest /Users/davidfekke/Documents/android/projects
Using cordova-fetch for cordova-android@7.0.0
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.swyftmobile.sfhybridtest
	Name: SFHybridTest
	Activity: MainActivity
	Android target: android-26
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.0.0
Android Studio project detected
Android Studio project detected
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.

Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving android@~7.0.0 into config.xml file ...
/Users/davidfekke/Documents/android/projects
/Users/davidfekke/Documents/android/projects/SFHybridTest /Users/davidfekke/Documents/android/projects
Installing "com.salesforce" for android
Plugin dependency "cordova-plugin-whitelist@1.3.3" already fetched, using that version.
Dependent plugin "cordova-plugin-whitelist" already installed on android.
Failed to install 'com.salesforce': CordovaError: Failed to fetch plugin cordova-plugin-device@1.0.1 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:215:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/cordova-fetch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
/Users/davidfekke/Documents/android/projects
forcehybrid failed

Command failed: cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin#v6.0.0 --force
Error: Failed to fetch plugin cordova-plugin-device@1.0.1 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**Comment by wmathurin** [comment]
What cordova cli version are you using? Do `cordova --version` to find out.
Looking at https://github.com/ionic-team/ionic-cli/issues/2845#issuecomment-340492018 (and other similar issues), there might be a bug with fetching plugins in cordova cli 7.1.0. You should be okay if you using cordova cli 7.0.1.

**Comment by bhariharan** [comment]
This is a known issue with `node@8.x`. It should work with `node@6.x`. I have `node@6.2.2` installed.

**Comment by davidfekke** [comment]
That is a really old version of Node. We are using 8.9.4 internally here. Are there any plans to support recent version of Node, or should we look for that in the enhancements you are making into sfdx?

I downgraded my version of node to 6.12.3, and I was able to create a fresh project using `forcehybrid`.

**Comment by bhariharan** [comment]
We are looking at removing the dependency on `cordova-plugin-device`. Hopefully, that'll enable usage of `node@8.x`.
